### ISSUE TITLE
Uncaught Error: Class 'Image' not found in

### ISSUE THREAD

**Issue by ermukul008** [benmajor/PHP-Image-Resize#1]
Uncaught Error: Class 'Image' not found in index.php below is code

?php
require 'vendor/autoload.php';
use BenMajor\ImageResize;

$image = new Image('http://4.bp.blogspot.com/-wykO_6QC7Sk/Uemq1_yXg8I/AAAAAAAAAHY/dtBq0IneP08/s1600/maka.jpg');
$image->resizeHeight( 300 );
$image->output();
?>

**Comment by benmajor** [comment]
Thanks for your ticket, it looks like the `use` statement I added in the ReadMe is incorrect. You should use the following:

```
<?php
require 'vendor/autoload.php';
use BenMajor\ImageResize\Image;

$image = new Image('http://4.bp.blogspot.com/-wykO_6QC7Sk/Uemq1_yXg8I/AAAAAAAAAHY/dtBq0IneP08/s1600/maka.jpg');
$image->resizeHeight( 300 );
$image->output();
?>
```

I'll update the ReadMe now.

**Comment by benmajor** [comment]
This has now fixed with this commit:
https://github.com/benmajor/PHP-Image-Resize/commit/04c4dd7d02edbb413213c8e3f41958c34fc3736d

**Comment by ermukul008** [comment]
Not working, I am using composer install and my index file is in root directory.

**Comment by benmajor** [comment]
Do you see any errors in your code at all? Have you updated the `use` statement?

**Comment by ermukul008** [comment]
I have updated use statement.

Same error is coming still

**Comment by benmajor** [comment]
Can you share your `composer.json` file? I can't seem to replicate the issue.

**Comment by ermukul008** [comment]
{
    "name": "benmajor/php-image-resize",
    "description": "A simple PHP class to handle image resizing and editing.",
    "authors": [
        {
            "name": "Ben Major",
            "email": "ben.major88@gmail.com"
        }
    ],
    "license": "MIT",
    "require": {
        "php": ">= 5.6.0"
    },
    "autoload": {
        "psr-4": {
            "BenMajor\\ImageResize\\": "src/"
        }
    }
}

**Comment by benmajor** [comment]
Thanks - do you have the files included in the `vendor` directory?

**Comment by ermukul008** [comment]
yes

**Comment by ermukul008** [comment]
<?php

require 'vendor/autoload.php';
use BenMajor\ImageResize\Image;

$image = new Image('http://4.bp.blogspot.com/-wykO_6QC7Sk/Uemq1_yXg8I/AAAAAAAAAHY/dtBq0IneP08/s1600/maka.jpg');
$image->resizeHeight( 300 );
$image->output();
?>

**Comment by ermukul008** [comment]
<?php

require 'vendor/autoload.php';
use BenMajor\ImageResize\Image;

$image = new Image('http://4.bp.blogspot.com/-wykO_6QC7Sk/Uemq1_yXg8I/AAAAAAAAAHY/dtBq0IneP08/s1600/maka.jpg');
$image->resizeHeight( 300 );
$image->output();
?>

**Comment by benmajor** [comment]
I think I have found the issue. The PSR path was incorrect in the `composer.json` file. Can you please try removing and re-adding the project to your Composer install?

```
$ composer remove benmajor/php-image-resize
$ composer require benmajor/php-image-resize ^1.1.2
```

This should fix the issue.

**Comment by ermukul008** [comment]
fixed

**Comment by ermukul008** [comment]
thanks

**Comment by benmajor** [comment]
No problem, glad it worked out :)
