### ISSUE TITLE
Being able to open SVG files

### ISSUE THREAD

**Issue by nitodico** [benmajor/PHP-Image-Resize#3]
I've look up on docs and examples and cannot find any references to being able to open SVG files, not sure if is a bug or a feature not implemented yet. I know SVG are not technically plain images but being able to open such kind of files usually used on sites such Wikipedia or Open Street Maps would be awesome.

**Comment by benmajor** [comment]
Sadly the GD library, and thus the PHP extension for it does not support SVG, so I can't add support to the project without switching to Imagine.
